server {
    listen 80;

    root /home/ec2-user/Traktoros/frontend;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location /detect {
        proxy_pass http://127.0.0.1:5000;
        proxy_set_header Host $host;
        proxy_read_timeout 120s;
    }

    location /detect-bedrock {
        proxy_pass http://127.0.0.1:5000;
        proxy_set_header Host $host;
        proxy_read_timeout 120s;
    }

    location /quality {
        proxy_pass http://127.0.0.1:5000;
        proxy_set_header Host $host;
    }
}
